site_name: RE&CT
site_dir: site/
docs_dir: docs/

theme:
    name: null
    custom_dir: 'docs/readthedocs/'
    navigation_depth: 4
    search_index_only: true
    titles_only: true

repo_url: https://github.com/atc-project/atc-react
edit_uri: blob/master/docs/
google_analytics: ['UA-165240552-2', 'https://atc-project.github.io/atc-react/']

plugins:
    - awesome-pages
    - exclude:
        glob:
            - "*DS_Store"
            - "*.git"
            - "*.idea"
nav:
    - Introduction:
        - ATC DATA (EN): index.md
        - ATC DATA (RU): index_RU.md
    - ATC DATA:
        - Data Needed:
            - "DN0001_4688_windows_process_creation": ./Data_Needed/DN0001_4688_windows_process_creation.md
            - "DN0002_4688_windows_process_creation_with_commandline": ./Data_Needed/DN0002_4688_windows_process_creation_with_commandline.md
            - "DN0003_1_windows_sysmon_process_creation": ./Data_Needed/DN0003_1_windows_sysmon_process_creation.md
            - "DN0004_4624_windows_account_logon": ./Data_Needed/DN0004_4624_windows_account_logon.md
            - "DN0005_7045_windows_service_insatalled": ./Data_Needed/DN0005_7045_windows_service_insatalled.md
            - "DN0006_2_windows_sysmon_process_changed_a_file_creation_time": ./Data_Needed/DN0006_2_windows_sysmon_process_changed_a_file_creation_time.md
            - "DN0007_3_windows_sysmon_network_connection": ./Data_Needed/DN0007_3_windows_sysmon_network_connection.md
            - "DN0008_4_windows_sysmon_sysmon_service_state_changed": ./Data_Needed/DN0008_4_windows_sysmon_sysmon_service_state_changed.md
            - "DN0009_5_windows_sysmon_process_terminated": ./Data_Needed/DN0009_5_windows_sysmon_process_terminated.md
            - "DN0010_6_windows_sysmon_driver_loaded": ./Data_Needed/DN0010_6_windows_sysmon_driver_loaded.md
            - "DN0011_7_windows_sysmon_image_loaded": ./Data_Needed/DN0011_7_windows_sysmon_image_loaded.md
            - "DN0012_8_windows_sysmon_CreateRemoteThread": ./Data_Needed/DN0012_8_windows_sysmon_CreateRemoteThread.md
            - "DN0013_9_windows_sysmon_RawAccessRead": ./Data_Needed/DN0013_9_windows_sysmon_RawAccessRead.md
            - "DN0014_10_windows_sysmon_ProcessAccess": ./Data_Needed/DN0014_10_windows_sysmon_ProcessAccess.md
            - "DN0015_11_windows_sysmon_FileCreate": ./Data_Needed/DN0015_11_windows_sysmon_FileCreate.md
            - "DN0016_12_windows_sysmon_RegistryEvent": ./Data_Needed/DN0016_12_windows_sysmon_RegistryEvent.md
            - "DN0017_13_windows_sysmon_RegistryEvent": ./Data_Needed/DN0017_13_windows_sysmon_RegistryEvent.md
            - "DN0018_14_windows_sysmon_RegistryEvent": ./Data_Needed/DN0018_14_windows_sysmon_RegistryEvent.md
            - "DN0019_15_windows_sysmon_FileCreateStreamHash": ./Data_Needed/DN0019_15_windows_sysmon_FileCreateStreamHash.md
            - "DN0020_17_windows_sysmon_PipeEvent": ./Data_Needed/DN0020_17_windows_sysmon_PipeEvent.md
            - "DN0021_18_windows_sysmon_PipeEvent": ./Data_Needed/DN0021_18_windows_sysmon_PipeEvent.md
            - "DN0022_19_windows_sysmon_WmiEvent": ./Data_Needed/DN0022_19_windows_sysmon_WmiEvent.md
            - "DN0023_20_windows_sysmon_WmiEvent": ./Data_Needed/DN0023_20_windows_sysmon_WmiEvent.md
            - "DN0024_21_windows_sysmon_WmiEvent": ./Data_Needed/DN0024_21_windows_sysmon_WmiEvent.md
            - "DN0026_5136_windows_directory_service_object_was_modified": ./Data_Needed/DN0026_5136_windows_directory_service_object_was_modified.md
            - "DN0027_4738_user_account_was_changed": ./Data_Needed/DN0027_4738_user_account_was_changed.md
            - "DN0028_4794_directory_services_restore_mode_admin_password_set": ./Data_Needed/DN0028_4794_directory_services_restore_mode_admin_password_set.md
            - "DN0029_4661_handle_to_an_object_was_requested": ./Data_Needed/DN0029_4661_handle_to_an_object_was_requested.md
            - "DN0030_4662_operation_was_performed_on_an_object": ./Data_Needed/DN0030_4662_operation_was_performed_on_an_object.md
            - "DN0031_7036_service_started_stopped": ./Data_Needed/DN0031_7036_service_started_stopped.md
            - "DN0032_5145_network_share_object_was_accessed_detailed": ./Data_Needed/DN0032_5145_network_share_object_was_accessed_detailed.md
            - "DN0033_5140_network_share_object_was_accessed": ./Data_Needed/DN0033_5140_network_share_object_was_accessed.md
            - "DN0034_104_log_file_was_cleared": ./Data_Needed/DN0034_104_log_file_was_cleared.md
            - "DN0035_106_task_scheduler_task_registered": ./Data_Needed/DN0035_106_task_scheduler_task_registered.md
            - "DN0036_150_dns_server_could_not_load_dll": ./Data_Needed/DN0108_150_dns_server_could_not_load_dll.md
            - "DN0036_4104_windows_powershell_script_block": ./Data_Needed/DN0036_4104_windows_powershell_script_block.md
            - "DN0037_4103_windows_powershell_executing_pipeline": ./Data_Needed/DN0037_4103_windows_powershell_executing_pipeline.md
            - "DN0038_400_engine_state_is_changed_from_none_to_available": ./Data_Needed/DN0038_400_engine_state_is_changed_from_none_to_available.md
            - "DN0039_524_system_catalog_has_been_deleted": ./Data_Needed/DN0039_524_system_catalog_has_been_deleted.md
            - "DN0040_528_user_successfully_logged_on_to_a_computer": ./Data_Needed/DN0040_528_user_successfully_logged_on_to_a_computer.md
            - "DN0041_529_logon_failure": ./Data_Needed/DN0041_529_logon_failure.md
            - "DN0042_675_kerberos_preauthentication_failed": ./Data_Needed/DN0042_675_kerberos_preauthentication_failed.md
            - "DN0043_770_dns_server_plugin_dll_has_been_loaded": ./Data_Needed/DN0043_770_dns_server_plugin_dll_has_been_loaded.md
            - "DN0046_1031_dhcp_service_callout_dll_file_has_caused_an_exception": ./Data_Needed/DN0046_1031_dhcp_service_callout_dll_file_has_caused_an_exception.md
            - "DN0047_1032_dhcp_service_callout_dll_file_has_caused_an_exception": ./Data_Needed/DN0047_1032_dhcp_service_callout_dll_file_has_caused_an_exception.md
            - "DN0048_1033_dhcp_service_successfully_loaded_callout_dlls": ./Data_Needed/DN0048_1033_dhcp_service_successfully_loaded_callout_dlls.md
            - "DN0049_1034_dhcp_service_failed_to_load_callout_dlls": ./Data_Needed/DN0049_1034_dhcp_service_failed_to_load_callout_dlls.md
            - "DN0050_1102_audit_log_was_cleared": ./Data_Needed/DN0050_1102_audit_log_was_cleared.md
            - "DN0051_1121_attack_surface_reduction_blocking_mode_event": ./Data_Needed/DN0051_1121_attack_surface_reduction_blocking_mode_event.md
            - "DN0052_2003_query_to_load_usb_drivers": ./Data_Needed/DN0052_2003_query_to_load_usb_drivers.md
            - "DN0053_2100_pnp_or_power_operation_for_usb_device": ./Data_Needed/DN0053_2100_pnp_or_power_operation_for_usb_device.md
            - "DN0054_2102_pnp_or_power_operation_for_usb_device": ./Data_Needed/DN0054_2102_pnp_or_power_operation_for_usb_device.md
            - "DN0054_linux_auditd_execve": ./Data_Needed/DN0054_linux_auditd_execve.md
            - "DN0055_linux_auditd_read_access_to_file": ./Data_Needed/DN0055_linux_auditd_read_access_to_file.md
            - "DN0056_linux_auditd_syscall": ./Data_Needed/DN0056_linux_auditd_syscall.md
            - "DN0057_4625_account_failed_to_logon": ./Data_Needed/DN0057_4625_account_failed_to_logon.md
            - "DN0058_4656_handle_to_an_object_was_requested": ./Data_Needed/DN0058_4656_handle_to_an_object_was_requested.md
            - "DN0059_4657_registry_value_was_modified": ./Data_Needed/DN0059_4657_registry_value_was_modified.md
            - "DN0060_4658_handle_to_an_object_was_closed": ./Data_Needed/DN0060_4658_handle_to_an_object_was_closed.md
            - "DN0061_4660_object_was_deleted": ./Data_Needed/DN0061_4660_object_was_deleted.md
            - "DN0062_4663_attempt_was_made_to_access_an_object": ./Data_Needed/DN0062_4663_attempt_was_made_to_access_an_object.md
            - "DN0063_4697_service_was_installed_in_the_system": ./Data_Needed/DN0063_4697_service_was_installed_in_the_system.md
            - "DN0064_4698_scheduled_task_was_created": ./Data_Needed/DN0064_4698_scheduled_task_was_created.md
            - "DN0065_4701_scheduled_task_was_disabled": ./Data_Needed/DN0065_4701_scheduled_task_was_disabled.md
            - "DN0066_4704_user_right_was_assigned": ./Data_Needed/DN0066_4704_user_right_was_assigned.md
            - "DN0067_4719_system_audit_policy_was_changed": ./Data_Needed/DN0067_4719_system_audit_policy_was_changed.md
            - "DN0068_4728_member_was_added_to_security_enabled_global_group": ./Data_Needed/DN0068_4728_member_was_added_to_security_enabled_global_group.md
            - "DN0069_4732_member_was_added_to_security_enabled_local_group": ./Data_Needed/DN0069_4732_member_was_added_to_security_enabled_local_group.md
            - "DN0070_4735_security_enabled_local_group_was_changed": ./Data_Needed/DN0070_4735_security_enabled_local_group_was_changed.md
            - "DN0071_4737_security_enabled_global_group_was_changed": ./Data_Needed/DN0071_4737_security_enabled_global_group_was_changed.md
            - "DN0072_4755_security_enabled_universal_group_was_changed": ./Data_Needed/DN0072_4755_security_enabled_universal_group_was_changed.md
            - "DN0073_4756_member_was_added_to_a_security_enabled_universal_group": ./Data_Needed/DN0073_4756_member_was_added_to_a_security_enabled_universal_group.md
            - "DN0074_4765_sid_history_was_added_to_an_account": ./Data_Needed/DN0074_4765_sid_history_was_added_to_an_account.md
            - "DN0075_4766_attempt_to_add_sid_history_to_an_account_failed": ./Data_Needed/DN0075_4766_attempt_to_add_sid_history_to_an_account_failed.md
            - "DN0076_4768_kerberos_authentication_ticket_was_requested": ./Data_Needed/DN0076_4768_kerberos_authentication_ticket_was_requested.md
            - "DN0077_4769_kerberos_service_ticket_was_requested": ./Data_Needed/DN0077_4769_kerberos_service_ticket_was_requested.md
            - "DN0078_4771_kerberos_pre_authentication_failed": ./Data_Needed/DN0078_4771_kerberos_pre_authentication_failed.md
            - "DN0079_4776_computer_attempted_to_validate_the_credentials_for_an_account": ./Data_Needed/DN0079_4776_computer_attempted_to_validate_the_credentials_for_an_account.md
            - "DN0080_5859_wmi_activity": ./Data_Needed/DN0080_5859_wmi_activity.md
            - "DN0081_5861_wmi_activity": ./Data_Needed/DN0081_5861_wmi_activity.md
            - "DN0082_8002_ntlm_server_blocked_audit": ./Data_Needed/DN0082_8002_ntlm_server_blocked_audit.md
            - "DN0083_16_access_history_in_hive_was_cleared": ./Data_Needed/DN0083_16_access_history_in_hive_was_cleared.md
            - "DN0084_av_alert": ./Data_Needed/DN0084_av_alert.md
            - "DN0085_22_windows_sysmon_DnsQuery": ./Data_Needed/DN0085_22_windows_sysmon_DnsQuery.md
            - "DN0086_4720_user_account_was_created": ./Data_Needed/DN0086_4720_user_account_was_created.md
            - "DN0087_5156_windows_filtering_platform_has_permitted_connection": ./Data_Needed/DN0087_5156_windows_filtering_platform_has_permitted_connection.md
            - "DN0088_4616_system_time_was_changed": ./Data_Needed/DN0088_4616_system_time_was_changed.md
            - "DN0089_56_terminal_server_security_layer_detected_an_error": ./Data_Needed/DN0089_56_terminal_server_security_layer_detected_an_error.md
            - "DN0090_50_terminal_server_security_layer_detected_an_error": ./Data_Needed/DN0090_50_terminal_server_security_layer_detected_an_error.md
            - "DN0091_linux_modsecurity_log": ./Data_Needed/DN0091_linux_modsecurity_log.md
            - "DN0092_unix_generic_syslog": ./Data_Needed/DN0092_unix_generic_syslog.md
            - "DN0093_linux_clamav_log": ./Data_Needed/DN0093_linux_clamav_log.md
            - "DN0094_linux_sshd_log": ./Data_Needed/DN0094_linux_sshd_log.md
            - "DN0095_linux_auth_pam_log": ./Data_Needed/DN0095_linux_auth_pam_log.md
            - "DN0096_linux_named_client_security_log": ./Data_Needed/DN0096_linux_named_client_security_log.md
            - "DN0097_linux_daemon_log": ./Data_Needed/DN0097_linux_daemon_log.md
            - "DN0098_linux_vsftpd_log": ./Data_Needed/DN0098_linux_vsftpd_log.md
            - "DN0099_Bind_DNS_query": ./Data_Needed/DN0099_Bind_DNS_query.md
            - "DN0100_Passive_DNS_log": ./Data_Needed/DN0100_Passive_DNS_log.md
            - "DN_0044_1000_application_crashed": ./Data_Needed/DN0044_1000_application_crashed.md
            - "DN_0045_1001_windows_error_reporting": ./Data_Needed/DN0045_1001_windows_error_reporting.md
        - Logging Policy:
            - "LP0001_windows_audit_process_creation": ./Logging_Policy/LP0001_windows_audit_process_creation.md
            - "LP0002_windows_audit_process_creation_with_commandline": ./Logging_Policy/LP0002_windows_audit_process_creation_with_commandline.md
            - "LP0003_windows_sysmon_process_creation": ./Logging_Policy/LP0003_windows_sysmon_process_creation.md
            - "LP0004_windows_audit_logon": ./Logging_Policy/LP0004_windows_audit_logon.md
            - "LP0005_windows_sysmon_network_connection": ./Logging_Policy/LP0005_windows_sysmon_network_connection.md
            - "LP0006_windows_sysmon_image_loaded": ./Logging_Policy/LP0006_windows_sysmon_image_loaded.md
            - "LP0007_windows_sysmon_ProcessAccess": ./Logging_Policy/LP0007_windows_sysmon_ProcessAccess.md
            - "LP0008_windows_sysmon_FileCreate": ./Logging_Policy/LP0008_windows_sysmon_FileCreate.md
            - "LP0009_windows_sysmon_PipeEvent": ./Logging_Policy/LP0009_windows_sysmon_PipeEvent.md
            - "LP0010_windows_sysmon_WmiEvent": ./Logging_Policy/LP0010_windows_sysmon_WmiEvent.md
            - "LP0011_windows_sysmon_DnsQuery": ./Logging_Policy/LP0011_windows_sysmon_DnsQuery.md
            - "LP0025_audit_directory_service_changes": ./Logging_Policy/LP0025_windows_audit_directory_service_changes.md
            - "LP0026_windows_audit_user_account_management": ./Logging_Policy/LP0026_windows_audit_user_account_management.md
            - "LP0027_windows_audit_directory_service_access": ./Logging_Policy/LP0027_windows_audit_directory_service_access.md
            - "LP0028_windows_audit_sam": ./Logging_Policy/LP0028_windows_audit_sam.md
            - "LP0029_windows_audit_detailed_file_share": ./Logging_Policy/LP0029_windows_audit_detailed_file_share.md
            - "LP0030_windows_audit_file_share": ./Logging_Policy/LP0030_windows_audit_file_share.md
            - "LP0031_linux_auditd_execve": ./Logging_Policy/LP0031_linux_auditd_execve.md
            - "LP0032_linux_auditd_read_access_to_file": ./Logging_Policy/LP0032_linux_auditd_read_access_to_file.md
            - "LP0033_linux_auditd_syscall": ./Logging_Policy/LP0033_linux_auditd_syscall.md
            - "LP0034_linux_named_client_security_log": ./Logging_Policy/LP0034_linux_named_client_security_log.md
            - "LP0037_windows_audit_audit_policy_change": ./Logging_Policy/LP0037_windows_audit_audit_policy_change.md
            - "LP0038_windows_audit_kerberos_authentication_service": ./Logging_Policy/LP0038_windows_audit_kerberos_authentication_service.md
            - "LP0039_windows_audit_kernel_object": ./Logging_Policy/LP0039_windows_audit_kernel_object.md
            - "LP0041_windows_audit_other_object_access_events": ./Logging_Policy/LP0041_windows_audit_other_object_access_events.md
            - "LP0042_windows_audit_handle_manipulation": ./Logging_Policy/LP0042_windows_audit_handle_manipulation.md
            - "LP0044_windows_ntlm_audit": ./Logging_Policy/LP0044_windows_ntlm_audit.md
            - "LP0045_windows_audit_filtering_platform_connection": ./Logging_Policy/LP0045_windows_audit_filtering_platform_connection.md
            - "LP0046_windows_audit_security_state_change": ./Logging_Policy/LP0046_windows_audit_security_state_change.md
            - "LP0047_BIND_DNS_queries": ./Logging_Policy/LP0047_BIND_DNS_queries.md
            - "LP0048_Passive_DNS_logging": ./Logging_Policy/LP0048_Passive_DNS_logging.md
            - "LP0100_windows_audit_security_system_extension": ./Logging_Policy/LP0100_windows_audit_security_system_extension.md
            - "LP0101_windows_audit_security_group_management": ./Logging_Policy/LP0101_windows_audit_security_group_management.md
            - "LP0102_windows_audit_file_system": ./Logging_Policy/LP0102_windows_audit_file_system.md
            - "LP0103_windows_audit_registry": ./Logging_Policy/LP0103_windows_audit_registry.md
            - "LP0104_windows_audit_removable_storage": ./Logging_Policy/LP0104_windows_audit_removable_storage.md
            - "LP0105_windows_audit_authorization_policy_change": ./Logging_Policy/LP0105_windows_audit_authorization_policy_change.md
            - "LP0106_windows_audit_kerberos_service_ticket_operations": ./Logging_Policy/LP0106_windows_audit_kerberos_service_ticket_operations.md
            - "LP0107_windows_audit_credential_validation": ./Logging_Policy/LP0107_windows_audit_credential_validation.md
            - "LP0108_windows_powershell_module_logging": ./Logging_Policy/LP0108_windows_powershell_module_logging.md
            - "LP0109_windows_powershell_script_block_logging": ./Logging_Policy/LP0109_windows_powershell_script_block_log.md
            - "LP0110_windows_powershell_transcript": ./Logging_Policy/LP0110_windows_powershell_transcript.md
        - Enrichments:
            - "EN0001_cache_sysmon_event_id_1_info": ./Enrichments/EN0001_cache_sysmon_event_id_1_info.md
            - "EN0002_enrich_sysmon_event_id_1_with_parent_info": ./Enrichments/EN0002_enrich_sysmon_event_id_1_with_parent_info.md
            - "EN0003_enrich_other_sysmon_events_with_event_id_1_data": ./Enrichments/EN0003_enrich_other_sysmon_events_with_event_id_1_data.md
            - "EN0004_enrich_sysmon_event_id_11_with_TargetFilePathFingerprint": ./Enrichments/EN0004_enrich_sysmon_event_id_11_with_TargetFilePathFingerprint.md
            - "EN0005_cache_TargetFilePathFingerprint_from_enriched_sysmon_event_id_11": ./Enrichments/EN0005_cache_TargetFilePathFingerprint_from_enriched_sysmon_event_id_11.md